name: codeguru review test

on:
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: 'ap-northeast-1'
        role-to-assume: 'arn:aws:iam::156041420462:role/codeguru-testing'

    - name: AWS CodeGuru Reviewer Scanner
      uses: aws-actions/codeguru-reviewer@v1.1
      if: ${{ always() }}
      with:
        build_path: target
        s3_bucket: arn:aws:s3:::codeguru-reviewer-codeguru-testing-ruby

    - name: Upload review result
      if: ${{ github.event_name != 'push' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeguru-results.sarif.json

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v2
